export const NEW_PROJECT_REQUEST = "NEW_PROJECT_REQUEST";
export const NEW_PROJECT_SUCCESS = "NEW_PROJECT_SUCCESS";
export const NEW_PROJECT_RESET = "NEW_PROJECT_RESET";
export const NEW_PROJECT_FAIL = "NEW_PROJECT_FAIL";

export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST";
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS";
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_RESET = "DELETE_PROJECT_RESET";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const NEW_TASK_REQUEST = "NEW_TASK_REQUEST";
export const NEW_TASK_SUCCESS = "NEW_TASK_SUCCESS";
export const NEW_TASK_RESET = "NEW_TASK_RESET";
export const NEW_TASK_FAIL = "NEW_TASK_FAIL";

export const ALL_TASK_REQUEST = "ALL_TASK_REQUEST";
export const ALL_TASK_SUCCESS = "ALL_TASK_SUCCESS";
export const ALL_TASK_FAIL = "ALL_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";